import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingTop: 60,
    backgroundColor: theme.colors.grey[850],
    paddingBottom: 20,
    paddingHorizontal: theme.spacing.lg,
  },
  title: {
    fontSize: 24,
    fontWeight: '900',
    color: theme.colors.primary,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.text.secondary,
    marginBottom: 20,
  },
  pathSelector: {
    flexDirection: 'row',
    marginTop: 15,
  },
  pathTab: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 22,
    marginRight: 10,
    borderWidth: 1,
    borderColor: theme.colors.grey[500],
    backgroundColor: theme.colors.grey[800],
  },
  activePathTab: {
    backgroundColor: theme.colors.primary + '25',
    borderColor: theme.colors.primary,
  },
  pathTabText: {
    color: theme.colors.grey[100],
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  activePathTabText: {
    color: theme.colors.primary,
  },
  exerciseMap: {
    padding: 20,
    alignItems: 'center',
    backgroundColor: theme.colors.grey[900],
    marginVertical: 10,
  },
  mapRow: {
     flexDirection: 'row',
     flexWrap: 'wrap',
     justifyContent: 'center',
     width: '100%',
     paddingHorizontal: 10,
  },
  levelCircle: {
     width: 55,
     height: 55,
     borderRadius: 14,
     backgroundColor: theme.colors.grey[750],
     borderWidth: 1,
     borderColor: theme.colors.grey[500],
     justifyContent: 'center',
     alignItems: 'center',
     margin: 6, 
  },
  activeLevelCircle: {
     borderColor: theme.colors.accent,
     backgroundColor: theme.colors.grey[650],
     shadowColor: theme.colors.accent,
     shadowOffset: { width: 0, height: 0 },
     shadowOpacity: 0.6,
     shadowRadius: 10,
     elevation: 6,
     borderWidth: 2,
  },
  levelText: {
     color: theme.colors.grey[200],
     fontWeight: '900',
     fontSize: 16,
  },
  activeLevelText: {
     color: theme.colors.accent,
  },
  exerciseCard: {
     backgroundColor: theme.colors.surface,
     padding: 20,
     borderRadius: 20,
     marginHorizontal: 20,
     marginBottom: 40,
     borderWidth: 1,
     borderColor: theme.colors.border,
     shadowColor: theme.colors.grey[900],
     shadowOffset: { width: 0, height: 10 },
     shadowOpacity: 0.3,
     shadowRadius: 15,
     elevation: 10,
  },
  exTitle: {
     fontSize: 20,
     fontWeight: '900',
     color: theme.colors.primary,
     marginBottom: 12,
  },
  exDesc: {
     color: theme.colors.text.secondary,
     fontSize: 14,
     lineHeight: 22,
     marginBottom: 18,
  },
  exParams: {
     backgroundColor: theme.colors.grey[900],
     padding: 15,
     borderRadius: 14,
     flexDirection: 'row',
     justifyContent: 'space-between',
     marginBottom: 15,
     borderWidth: 1,
     borderColor: theme.colors.grey[700],
  },
  paramLabel: {
     color: theme.colors.grey[300],
     fontSize: 10,
     fontWeight: '800',
     textTransform: 'uppercase',
     marginBottom: 2,
  },
  paramValue: {
     color: theme.colors.text.primary,
     fontSize: 13,
     fontWeight: '900',
  },
  btnSolve: {
     backgroundColor: theme.colors.primary,
     height: 54,
     borderRadius: 14,
     justifyContent: 'center',
     alignItems: 'center',
     marginTop: 20,
     shadowColor: theme.colors.primary,
     shadowOffset: { width: 0, height: 5 },
     shadowOpacity: 0.4,
     shadowRadius: 10,
     elevation: 8,
  },
  btnLabel: {
     color: theme.colors.text.primary,
     fontWeight: '900',
     fontSize: 16,
  },
  quizInput: {
    flex: 1,
    height: 40,
    backgroundColor: theme.colors.grey[800],
    borderRadius: 8,
    paddingHorizontal: 12,
    color: theme.colors.text.primary,
    borderWidth: 1,
    borderColor: theme.colors.grey[500],
    fontSize: 14,
  },
  quizInputActive: {
    borderColor: theme.colors.primary,
    borderWidth: 1.5,
  },
  quizStep: {
    backgroundColor: theme.colors.grey[900],
    padding: 15,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.grey[700],
    marginBottom: 15,
    opacity: 0.5,
  },
  quizStepDone: {
    borderColor: theme.colors.primary + '40',
    backgroundColor: theme.colors.primary + '08',
    opacity: 1,
  },
  stepTitle: {
    color: theme.colors.primary,
    fontWeight: '900',
    fontSize: 13,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  stepInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  stepLabel: {
    color: theme.colors.text.secondary,
    fontWeight: 'bold',
    fontSize: 14,
  },
  checkBtn: {
    backgroundColor: theme.colors.primary,
    width: 40,
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
  successText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
});
